#!/bin/bash
USAGE="A parallel check dns zone transfer script.
Usage: `basename $0` [-h] [-j njob] [-o output_directory] domainlist_file or domain"

J=1
O="."

while getopts hj:o: opt; do
  case $opt in
    h) echo "$USAGE"
      exit 0 ;;
    j) J=$OPTARG ;;
    o) O=$OPTARG ;;
    \?) echo "$USAGE"
      exit 1 ;;
  esac
done

shift $(($OPTIND-1))
F=$1

[[ ! -d "$O" ]] && mkdir "$O"

CMD() {
  for n in `dig NS $1 +short 2>/dev/null`; do 
    r=`dig @$n AXFR $1 +short 2>/dev/null` 
    if [[ $? -eq 0 && "$r" != "; Transfer failed." ]]; then
      echo "$1"
      echo "$r" > $O/dns_$1.$2
      break
    fi
  done
}

if [ -f "$F" ]; then
  tmpfile="/tmp/$$.fifo"
  mkfifo "$tmpfile"
  exec 6<>"$tmpfile"
  rm -rf "$tmpfile"

  for ((i=0; i<$J; i++)); do
    echo
  done >&6

  i=0
  while read line; do
    i=$((i+1))
    read -u 6
    {
      #echo $line
      CMD "$line" $i
      sleep 2
      echo >&6
    } &
  done < $F

  wait
  exec 6>&-

elif [ "$F" ]; then
  CMD "$F" 1
else
  echo "$USAGE"
  exit 1
fi

exit 0
